import secrets
import time
from datetime import datetime, timezone

from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import check_password_hash, generate_password_hash

from db import db, User, InviteCode

auth_bp = Blueprint("auth", __name__)

# Very small in-memory login throttle. Good enough for a small internal
# team tool; for larger deployments swap this for Flask-Limiter + Redis.
_failed_attempts = {}  # key: ip+email -> (count, last_attempt_ts)
_MAX_ATTEMPTS = 5
_LOCKOUT_SECONDS = 300


def _throttle_key():
    return f"{request.remote_addr}:{request.form.get('email', '').lower()}"


def _is_locked_out(key):
    entry = _failed_attempts.get(key)
    if not entry:
        return False
    count, last_ts = entry
    if count < _MAX_ATTEMPTS:
        return False
    return (time.time() - last_ts) < _LOCKOUT_SECONDS


def _record_failure(key):
    count, _ = _failed_attempts.get(key, (0, 0))
    _failed_attempts[key] = (count + 1, time.time())


def _clear_failures(key):
    _failed_attempts.pop(key, None)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    if request.method == "POST":
        key = _throttle_key()
        if _is_locked_out(key):
            flash("Too many failed attempts. Try again in a few minutes.", "error")
            return render_template("login.html")

        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password_hash, password):
            _clear_failures(key)
            login_user(user, remember=False)
            session.permanent = True
            user.last_login_at = datetime.now(timezone.utc)
            db.session.commit()
            return redirect(url_for("main.dashboard"))

        _record_failure(key)
        flash("Invalid email or password.", "error")

    return render_template("login.html")


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    """
    Registration requires a valid, unused invite code generated by an
    existing team admin (see /admin/invite). This keeps signup closed
    to the team without anyone needing to hardcode a roster.
    """
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))

    if request.method == "POST":
        code_str = request.form.get("invite_code", "").strip()
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        confirm = request.form.get("confirm_password", "")

        invite = InviteCode.query.filter_by(code=code_str, used_by=None).first()
        if not invite:
            flash("Invalid or already-used invite code.", "error")
            return render_template("register.html")

        if not name or not email or not password:
            flash("All fields are required.", "error")
            return render_template("register.html")

        if password != confirm:
            flash("Passwords do not match.", "error")
            return render_template("register.html")

        if len(password) < 10:
            flash("Password must be at least 10 characters.", "error")
            return render_template("register.html")

        if User.query.filter_by(email=email).first():
            flash("An account with that email already exists.", "error")
            return render_template("register.html")

        user = User(
            email=email,
            name=name,
            password_hash=generate_password_hash(password),
        )
        db.session.add(user)
        db.session.flush()

        invite.used_by = user.id
        invite.used_at = datetime.now(timezone.utc)
        db.session.commit()

        login_user(user)
        flash("Welcome! Your account has been created.", "success")
        return redirect(url_for("main.dashboard"))

    return render_template("register.html")


@auth_bp.route("/admin/invite", methods=["GET", "POST"])
@login_required
def create_invite():
    if not current_user.is_admin:
        flash("Only admins can generate invite codes.", "error")
        return redirect(url_for("main.dashboard"))

    new_code = None
    if request.method == "POST":
        new_code = secrets.token_urlsafe(12)
        invite = InviteCode(code=new_code, created_by=current_user.id)
        db.session.add(invite)
        db.session.commit()

    pending = InviteCode.query.filter_by(used_by=None).order_by(InviteCode.created_at.desc()).all()
    return render_template("invite.html", new_code=new_code, pending=pending)
